Repository SOPT-33RD-APP-NAVERPAY/NaverPay-Server, pull requests merged in 2023-11, with the labels that each got.

#2 [CHORE] 프로젝트 초기 세팅
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/sopt/org/NaverPay/NaverPayApplication.java
  src/main/java/sopt/org/NaverPay/common/ApiResponse.java
  src/main/java/sopt/org/NaverPay/common/ErrorType.java
  src/main/java/sopt/org/NaverPay/common/SuccessType.java
  src/main/java/sopt/org/NaverPay/controller/example.txt
  src/main/java/sopt/org/NaverPay/domain/example.txt
  src/main/java/sopt/org/NaverPay/dto/example.txt
  src/main/java/sopt/org/NaverPay/exception/CustomException.java
  src/main/java/sopt/org/NaverPay/repository/example.txt
  src/main/java/sopt/org/NaverPay/service/example.txt
  src/test/java/sopt/org/NaverPay/NaverPayApplicationTests.java
Labels: 예진🐰, 👑Feat, 📃Docs

#5 [FEAT] Point, Payment Entity 클래스 설계
  src/main/java/sopt/org/NaverPay/NaverPayApplication.java
  src/main/java/sopt/org/NaverPay/domain/basetime/BaseTimeEntity.java
  src/main/java/sopt/org/NaverPay/domain/brand/Brand.java
  src/main/java/sopt/org/NaverPay/domain/brand/BrandLike.java
  src/main/java/sopt/org/NaverPay/domain/brand/BrandLikeId.java
  src/main/java/sopt/org/NaverPay/domain/brand/DiscountType.java
  src/main/java/sopt/org/NaverPay/domain/example.txt
  src/main/java/sopt/org/NaverPay/domain/payment/Payment.java
  src/main/java/sopt/org/NaverPay/domain/point/Point.java
  src/main/java/sopt/org/NaverPay/domain/point/PointType.java
  src/main/java/sopt/org/NaverPay/domain/user/User.java
Labels: 예진🐰, 👑Feat

#10 [FEAT] 혜택 내역 조회 및 추천 브랜드 조회 API 개발
  src/main/java/sopt/org/NaverPay/controller/brand/BrandController.java
  src/main/java/sopt/org/NaverPay/controller/brand/dto/example.txt
  src/main/java/sopt/org/NaverPay/controller/brand/dto/response/BrandDto.java
  src/main/java/sopt/org/NaverPay/controller/brand/dto/response/GetBenefitBrandResponseDto.java
  src/main/java/sopt/org/NaverPay/controller/brand/dto/response/GetRecommendBrandResponseDto.java
  src/main/java/sopt/org/NaverPay/controller/dto/example.txt
  src/main/java/sopt/org/NaverPay/domain/brand/Brand.java
  src/main/java/sopt/org/NaverPay/domain/brand/DiscountType.java
  src/main/java/sopt/org/NaverPay/domain/point/Point.java
  src/main/java/sopt/org/NaverPay/domain/user/User.java
  src/main/java/sopt/org/NaverPay/global/exception/ErrorType.java
  src/main/java/sopt/org/NaverPay/global/exception/SuccessType.java
  src/main/java/sopt/org/NaverPay/repository/brand/BrandLikeRepository.java
  src/main/java/sopt/org/NaverPay/repository/brand/BrandRepository.java
  src/main/java/sopt/org/NaverPay/repository/user/UserRepository.java
  src/main/java/sopt/org/NaverPay/service/brand/BrandService.java
  src/main/resources/data.sql
Labels: 예준🐈, 🦄Database, ✨API, 👑Feat

#13 [CHORE] 더미데이터 추가 및 dev 환경 분리
  src/main/resources/application-dev.yml
  src/main/resources/data.sql
Labels: 예준🐈, 🦄Database, 🧚🏻‍♀️Chore

#14 [FEAT] 현장 결제 장소 조회 API 개발
  src/main/java/sopt/org/NaverPay/controller/brand/dto/example.txt
  src/main/java/sopt/org/NaverPay/controller/example.txt
  src/main/java/sopt/org/NaverPay/controller/payment/PaymentController.java
  src/main/java/sopt/org/NaverPay/controller/payment/dto/response/BrandDto.java
  src/main/java/sopt/org/NaverPay/controller/payment/dto/response/DataDto.java
  src/main/java/sopt/org/NaverPay/controller/payment/dto/response/NearByBrandDto.java
  src/main/java/sopt/org/NaverPay/controller/payment/dto/response/OnSitePaymentBrandDto.java
  src/main/java/sopt/org/NaverPay/global/exception/SuccessType.java
  src/main/java/sopt/org/NaverPay/repository/brand/BrandRepository.java
  src/main/java/sopt/org/NaverPay/service/example.txt
  src/main/java/sopt/org/NaverPay/service/payment/PaymentService.java
  src/main/resources/data.sql
Labels: 예진🐰, 🦄Database, ✨API, 👑Feat

#21 [FIX] 추천 혜택 브랜드 조회 API 요청헤더 추가
  src/main/java/sopt/org/NaverPay/controller/brand/BrandController.java
  src/main/java/sopt/org/NaverPay/service/brand/BrandService.java
Labels: 예준🐈, ✨API, 🐞Fix
